### ISSUE TITLE
Illegal instruction (core dumped) ERROR

### ISSUE THREAD

**Issue by chiquif23** [czodrowskilab/VSFlow#9]
Hello, whenever I try to use vsflow I have the following error: 

Start: 02/09/2024, 12:58:15
Running in parallel mode on 2 threads
Downloading database pdb ...
Instrucción ilegal (`core' generado)

"Illegal instruction (core dumped)" in english

It is independent of the instruction given or how many cores I use.

Could anyone help me, please? 
Thanks!
G

**Comment by mrcblt** [comment]
Hello,

Thank you for reaching out. The message `Illegal instruction (core dumped)` has nothing to do with the `--cores` parameter, it indicates an incompatibility between your (Linux) system and the VSFlow program or libraries. It could be that your CPU is too old or there are incompatibilities between the CPU architecture and the libraries. Unfortunately, there is nothing we can do about this on our end. I would suggest to try it on another system if possible.

May I ask which installation method you used? The "classic way" or using Docker?

Best,
Marcel

**Comment by chiquif23** [comment]
Thanks for the quick reply Marcel. I used the classic way for installation. I have to install the dependencies one by one because using the environment file didn't work. 

I'm gonna try in another system and hopefully that solve it. 

Thanks again, 
G
